openapi: 3.0.1
info:
  title: DevQ-Screenshot-service
  description: DevQ - Screenshot-service
  version: 1.0.0
servers:
  - url: /api/v1
tags:
  - name: Generate screenshot
    description: Generate the screenshots for a project
paths:
  /generate:
    post:
      tags:
        - Generates the screens for the given repo on branch
      description: Trigger a code download, build the docker image, run docker image, take screens , upload the to GC storage
      requestBody:
        description: Repo metadata
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RepoRequest'
        required: true
      responses:
        200:
          description: Returns success
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/GenerateResponse'
  /diff:
    post:
      tags:
        - Generates the diff images
      description: Given the project id it computes the diff for all the scenarios of a given project
      requestBody:
        description: Project id
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DiffRequest'
        required: true
      responses:
        200:
          description: Returns success
          content: {}
  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
          content: {}
components:
  schemas:
    RepoRequest:
      title: RepoRequest
      required:
        - projectId
        - user
        - repo
        - branch
      type: object
      properties:
        projectId:
          type: number
          example: 1
        user:
          type: string
          example: Assist-DevQ
        repo:
          type: string
          example: platform-bim
        branch:
          type: string
          example: master
    GenerateResponse:
      title: GenerateResponse
      required:
        - files
      type: object
      properties:
        files:
          type: array
          items:
            $ref: '#/components/schemas/ScenarioScreens'
    ScenarioScreens:
      title: ScenarioScreens
      required:
        - scenarioId
        - files
      type: object
      properties:
        scenarioId:
          type: number
          example: 12
        files:
          type: array
          items:
            type: string
            example: 'https://storage.googleapis.com/dev-q-screens/1575277729589-start-.png'
    DiffRequest:
      title: DiffRequest
      required:
        - projectId
      type: object
      properties:
        projectId:
          type: number
          example: 1
