openapi: 3.0.1
info:
  title: DevQ-Screenshot-service
  description: DevQ - Screenshot-service
  version: 1.0.0
servers:
  - url: /api/v1
tags:
  - name: Generate screenshot
    description: Generate the screenshots for a project
paths:
  /generate:
    post:
      tags:
        - Generates the screens for the given repo on branch
      description: Trigger a code download, build the docker image, run docker image, take screens , upload the to GC storage
      requestBody:
        description: Repo metadata
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RepoRequest'
        required: true
      responses:
        200:
          description: Returns success
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/GenerateResponse'
  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
          content: {}
components:
  schemas:
    RepoRequest:
      title: RepoRequest
      required:
        - projectId
        - user
        - repo
        - baseBranch
        - diffBranch
      type: object
      properties:
        projectId:
          type: number
          example: 1
        user:
          type: string
          example: Assist-DevQ
        repo:
          type: string
          example: platform-bim
        baseBranch:
          type: string
          example: master
        diffBranch:
          type: string
          example: master
    GenerateResponse:
      title: GenerateResponse
      required:
        - files
      type: object
      properties:
        files:
          type: array
          items:
            $ref: '#/components/schemas/ScenarioScreens'
    ScenarioScreens:
      title: ScenarioScreens
      required:
        - meta
        - files
      type: object
      properties:
        meta:
          type: object
          $ref: '#/components/schemas/ScreenMeta'
        files:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/ScreenFile'
    ScreenMeta:
      title: ScreenMeta
      required:
        - commitId
        - projectId
        - scenarioId
      type: object
      properties:
        commitId:
          type: string
          example: 376fefd
        projectId:
          type: number
          example: 11
        scenarioId:
          type: number
          example: 4
    ScreenFile:
      title: ScreenFile
      required:
        - eventId
        - baseFileUrl
        - diffFileUrl
      type: object
      properties:
        eventId:
          type: number
          example: 23
        baseFileUrl:
          type: string
          example: https://storage.googleapis.com/dev-q-screens/376fefd-11-4-23-base-click-.png
        diffFileUrl:
          type: string
          example: https://storage.googleapis.com/dev-q-screens/376fefd-11-4-23-diff-click-.png
